### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by liamb8** [nestordemeure/GPTranslate#2]
Hello, I'm trying to run your program using VSCode and I'm not seeing where to put the API key as there isn't a env file or somewhere that has a variable for me to put my API key. Are you able to help with this?

**Comment by nestordemeure** [comment]
Hello!

Sorry, I could have sworn I put the information in the readme but apparently I forgot. You need to put the API key in the environment which you can do by running this in the command line before running the script:

```
export OPENAI_API_KEY="???"
```

(see [here](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety#:~:text=key%20safety%20measure.-,3.%20Use%20Environment%20Variables%20in%20place%20of%20your%20API%20key,-An%20environment%20variable) for more details)

Have a good day,
Nestor
